#!/usr/bin/env python3
"""
日报生成器 - 生成 Markdown 格式的交易日报
"""

from datetime import datetime
from signals import SignalRecorder

class DailyReporter:
    """日报生成器"""
    
    def __init__(self, recorder):
        """
        初始化日报生成器
        
        Args:
            recorder: SignalRecorder 实例
        """
        self.recorder = recorder
    
    def generate_report(self, date_str=None):
        """
        生成日报
        
        Args:
            date_str: 日期字符串 (YYYY-MM-DD)，默认今天
        
        Returns:
            str: Markdown 格式的日报
        """
        if date_str is None:
            date_str = datetime.now().strftime('%Y-%m-%d')
        
        # 获取当天信号
        signals = self.recorder.get_signals_by_date(date_str)
        
        # 获取统计数据
        stats = self.recorder.get_signal_stats(days=1)
        
        # 构建报告
        report = []
        report.append(f"# CryptoEmperor AI 交易日报")
        report.append(f"**日期**: {date_str}")
        report.append(f"**生成时间**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append("")
        
        # 概览
        report.append("## 📊 今日概览")
        report.append(f"- **总信号数**: {stats['total']}")
        report.append(f"- **买入信号**: {stats['buy']} 🟢")
        report.append(f"- **卖出信号**: {stats['sell']} 🔴")
        report.append(f"- **观望**: {stats['hold']} ⚪")
        report.append("")
        
        # 按交易对统计
        if stats['by_symbol']:
            report.append("## 📈 分币种统计")
            report.append("")
            report.append("| 交易对 | 买入 | 卖出 | 观望 | 总计 |")
            report.append("|--------|------|------|------|------|")
            
            for symbol, counts in sorted(stats['by_symbol'].items()):
                total = counts['buy'] + counts['sell'] + counts['hold']
                report.append(
                    f"| {symbol} | {counts['buy']} 🟢 | {counts['sell']} 🔴 | "
                    f"{counts['hold']} ⚪ | {total} |"
                )
            report.append("")
        
        # 信号详情
        if signals:
            report.append("## 📋 信号详情")
            report.append("")
            
            # 按交易对分组
            by_symbol = {}
            for signal in signals:
                symbol = signal['symbol']
                if symbol not in by_symbol:
                    by_symbol[symbol] = []
                by_symbol[symbol].append(signal)
            
            for symbol, symbol_signals in sorted(by_symbol.items()):
                report.append(f"### {symbol}")
                report.append("")
                
                for signal in symbol_signals:
                    time = signal['timestamp'].split('T')[1].split('.')[0]
                    signal_type = signal['signal']
                    price = signal['price']
                    rsi = signal['rsi']
                    
                    # 信号图标
                    if '买入' in signal_type:
                        icon = "🟢"
                    elif '卖出' in signal_type:
                        icon = "🔴"
                    else:
                        icon = "⚪"
                    
                    report.append(
                        f"- **{time}** {icon} {signal_type} | "
                        f"价格: ${price:,.2f} | RSI: {rsi:.2f}"
                    )
                    
                    # 额外元数据
                    if signal.get('metadata'):
                        meta = signal['metadata']
                        if 'price_change_percent' in meta:
                            change = meta['price_change_percent']
                            change_emoji = "📈" if change > 0 else "📉"
                            report.append(f"  - 24h: {change_emoji} {change:+.2f}%")
                        if 'volume' in meta:
                            volume = meta['volume'] / 1e6
                            report.append(f"  - 成交额: ${volume:.1f}M")
                
                report.append("")
        else:
            report.append("## 📋 信号详情")
            report.append("")
            report.append("*今日暂无信号记录*")
            report.append("")
        
        # 风险提示
        report.append("---")
        report.append("")
        report.append("**⚠️ 风险提示**: 本报告仅供参考，不构成投资建议。加密货币市场波动剧烈，请谨慎决策。")
        report.append("")
        report.append(f"*Generated by CryptoEmperor AI*")
        
        return "\n".join(report)
    
    def save_report(self, output_dir='reports', date_str=None):
        """
        保存日报到文件
        
        Args:
            output_dir: 输出目录
            date_str: 日期字符串 (YYYY-MM-DD)，默认今天
        
        Returns:
            str: 报告文件路径
        """
        import os
        from pathlib import Path
        
        if date_str is None:
            date_str = datetime.now().strftime('%Y-%m-%d')
        
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        report = self.generate_report(date_str)
        report_file = os.path.join(output_dir, f"report_{date_str}.md")
        
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        return report_file
